### PR TITLE
Remove pr-aduit-group.txt in bot messages. Fixes #637

### LINKED ISSUE #637: No pr-aduit-group.txt file mentioned by the bot
# Issue Description
While I posted a PR https://github.com/nnstreamer/nnstreamer/pull/2714 I noticed there is no `pr-aduit-group.txt` link triggered when a build failed.

The relevant code looks like these but I am not sure which file link is supposed to be instead.

https://github.com/nnstreamer/TAOS-CI/blob/5ee8727b367c42d4d00bd933767f0d09b316618d/ci/taos/plugins-staging/pr-postbuild-nnstreamer-ubuntu-apptest.sh#L202

https://github.com/nnstreamer/TAOS-CI/blob/5ee8727b367c42d4d00bd933767f0d09b316618d/ci/taos/plugins-staging/pr-postbuild-nnstreamer-ubuntu-apptest.sh#L425

How to Reproduce
===============
1. Go to https://github.com/nnstreamer/nnstreamer/pull/2714
2. Click `pr-audiot-group.txt` mentioned by the bot: https://github.com/nnstreamer/nnstreamer/pull/2714#issuecomment-690082460
3. 404 Error
image

### PR DESCRIPTION
**Pull request by kbumsik**
This patch removes pr-aduit-group.txt that doesn't exist anymore. The file link is replaced by the folder link.
In other words, `s/\/pr-aduit-group.txt//g`.

Discussion: #637

**Self evaluation:**
1. Build test: [ ]Passed [ ]Failed [*]Skipped
2. Run test: [ ]Passed [ ]Failed [* ]Skipped

---
This change is [Reviewable](https://reviewable.io/reviews/nnstreamer/taos-ci/638)

### CODE REVIEW

**Review by gichan-jang — APPROVED** [review]
LGTM!

File: ci/taos/plugins-staging/pr-postbuild-nnstreamer-ubuntu-apptest.sh [hunk 1]
```diff
@@ -199,7 +199,7 @@ function pr-postbuild-nnstreamer-ubuntu-apptest-run-queue() {
         cibot_report $TOKEN "failure" "${BOT_NAME}/pr-postbuild-nnstreamer-apptest" "$message" "${CISERVER}${PRJ_REPO_UPSTREAM}/ci/${dir_commit}/" "$GITHUB_WEBHOOK_API/statuses/$input_commit"
 
         # Comment a hint on failed PR to author.
-        message=":octocat: **cibot**: $user_id, apptest could not be completed. To find out the reasons, please go to ${CISERVER}/${PRJ_REPO_UPSTREAM}/ci/${dir_commit}/pr-aduit-group.txt"
+        message=":octocat: **cibot**: $user_id, apptest could not be completed. To find out the reasons, please go to ${CISERVER}/${PRJ_REPO_UPSTREAM}/ci/${dir_commit}"
```
Comment (leemgs) [inline ci/taos/plugins-staging/pr-postbuild-nnstreamer-ubuntu-apptest.sh:202]: Nice catch.

**Review by leemgs — APPROVED** [review]
LGTM
